submit50:
  files:
    - !require "SDLFramework/main.cpp"  # SDLFramework 폴더 존재 확인용
    - !include "SDLFramework/**/*"      # 모든 파일 포함
  validate:
    - !exists "SDLFramework/"          # SDLFramework 폴더 존재 검증
  style: false
